# Generated by Django 2.2.9 on 2019-12-26 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191221_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='username',
            new_name='display_name',
        ),
    ]
